  <%
    socket = [
    ENV["DATABASE_MYSQL_SOCKET"]
    ].detect { |f| f && File.exist?(f) }
    %>

  default: &default
    adapter: mysql2
    pool: 5
    timeout: 5000

  development:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] %>
    <% if socket %>
    socket: <%= socket %>
    <% end %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] %>
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>

  test:
    <<: *default
    database: <%= ENV['DATABASE_NAME_TEST'] %>
    <% if socket %>
    socket: <%= socket %>
    <% end %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] %>
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>

  production:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] %>
    <% if socket %>
    socket: <%= socket %>
    <% end %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] %>
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>

  staging:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] %>
    <% if socket %>
    socket: <%= socket %>
    <% end %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] %>
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
